const PDFDocument = require('pdfkit');

function generateBeyondersPDF(data) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margins: { top: 50, bottom: 50, left: 50, right: 50 }
            });

            const chunks = [];
            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => {
                resolve({
                    success: true,
                    buffer: Buffer.concat(chunks)
                });
            });

            // Header
            doc.fontSize(24).fillColor('#2563eb').text('Beyonders 360 Assessment', { align: 'center' });
            doc.moveDown(0.5);
            doc.fontSize(16).fillColor('#64748b').text(data.test_title, { align: 'center' });
            doc.moveDown(2);

            // Candidate Info
            doc.rect(50, doc.y, 495, 100).fillColor('#f8fafc').stroke('#e2e8f0');
            const startY = doc.y + 20;

            doc.fontSize(12).fillColor('#1e293b');
            doc.text(`Candidate Name: ${data.student_name}`, 70, startY);
            doc.text(`Email: ${data.student_email}`, 70, startY + 20);
            doc.text(`Date: ${new Date().toLocaleDateString()}`, 70, startY + 40);

            doc.moveDown(4);

            // Score Section
            const scoreJson = data.score_json || {};
            const score = scoreJson.score || 0;
            const total = scoreJson.totalQuestions || 0;
            const correct = scoreJson.correctAnswers || 0;

            doc.fontSize(20).fillColor('#1e293b').text('Assessment Results', 50, doc.y);
            doc.moveDown(1);

            // Score Box
            const scoreBoxY = doc.y;
            doc.rect(50, scoreBoxY, 495, 120).fillColor('#eff6ff').fill();

            doc.fontSize(36).fillColor('#2563eb').text(`${score.toFixed(1)}%`, 0, scoreBoxY + 30, { align: 'center' });
            doc.fontSize(14).fillColor('#1e40af').text(`Score: ${correct} / ${total}`, 0, scoreBoxY + 80, { align: 'center' });

            doc.moveDown(4);

            // Footer
            doc.fontSize(10).fillColor('#94a3b8').text('Generated by ATRIA 360 Platform', 50, 750, { align: 'center' });

            doc.end();

        } catch (error) {
            reject(error);
        }
    });
}

module.exports = { generateBeyondersPDF };
